### PR TITLE
[template] go-support template

### PR DESCRIPTION
**Pull request by marcellanz**

### CODE REVIEW

**Comment by sleipnir** [comment]
Hi Marcel.

I tried to run make and got the following error message:

/root/go/pkg/mod/github.com/cloudstateio/go-support@v0.0.0-20191105163126-faaff6d92386/cloudstate/eventsourced_reply.go:70:5: undefined: errors.Is
/root/go/pkg/mod/github.com/cloudstateio/go-support@v0.0.0-20191105163126-faaff6d92386/cloudstate/eventsourced_reply.go:79:5: undefined: errors.Is
note: module requires Go 1.13make: ** [all] Erro 2

**Comment by sleipnir** [comment]
go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go/"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/sleipnir/development/workspace/pessoal/cloudstate-templates/templates/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build640379268=/tmp/go-build -gno-record-gcc-switches"

**Comment by marcellanz** [comment]
Hi Adriano

Error says:
> module requires Go 1.13

What version of Go do you use?

**Comment by sleipnir** [comment]
Sorry Marcel, I'm update go to 1.13.4 and then make run ok. But after this i got other error message on running shoppingcart binary:

[root@sleipnir go]# ./shoppingcart 
2019/11/05 17:48:51.637267 CloudState failed to run: unable to get environment variable "HOST"

**Comment by marcellanz** [comment]
> Sorry Marcel, I'm update go to 1.13.4 and then make run ok. But after this i got other error message on running shoppingcart binary:
> 
> [root@sleipnir go]# ./shoppingcart
> 2019/11/05 17:48:51.637267 CloudState failed to run: unable to get environment variable "HOST"

alright. now there are two environment variables needed for this implementation that comes right from the TCK example. HOST and PORT. you can run it like so:

HOST=127.0.0.1 PORT=8080 ./shoppingcart

**Comment by sleipnir** [comment]
Cool!
As long as it's in the documentation, I have no problem not accepting PR. But I would suggest a change in the path estructure of:

example/shoppingcart

for only:

shoppingcart

**Pull request merged**
